export { default as HomePage } from "./HomePage"
export { default as Dashboard } from "./Dashboard"
export { default as AddGoal } from "../components/AddGoal"
export { default as NotFound } from "./NotFound"
export { default as Profile } from "./Profile"
