import { useState } from "react"
import { GoalCreate, GoalSteps } from ".";

export default function AddGoal({ className }) {
  const [goal, setGoal] = useState({ name: "" });
  const [goalSelected, setGoalSelected] = useState(false);
  const [steps, setSteps] = useState(null);
  const [submitError, setSubmitError] = useState("");
  const defaultClasses = "body mt-16 max-w-7xl items-center justify-center";
  const combinedClasses = className ? `${defaultClasses} ${className}` : defaultClasses;

  // clear all fields, go to goal create screen
  function reset() {
    setGoal({ name: "" });
    setGoalSelected(false);
    setSteps(null);
    setSubmitError("");
  }

  return (
    <div className={combinedClasses}>
      <p className="paragraphStep"></p>

      <div className="goal-container shadow-lg">
        {/* if no goal has been submitted, display goal create form */}
        {!goalSelected ? (
          <>
            <GoalCreate
              goal={goal}
              setGoal={setGoal}
              setGoalSelected={setGoalSelected}
              setSteps={setSteps}
              setSubmitError={setSubmitError}
            ></GoalCreate>
          </>
        ) :
          // if goal has been submitted, render this
          <>
            {/* makes sure steps exist before rendering */}
            {steps ? (
              <GoalSteps
                steps={steps}
                setSteps={setSteps}
                reset={reset}
                goal={goal}
                setGoal={setGoal}
                setSubmitError={setSubmitError}
                usage="createGoal"
              ></GoalSteps>
            ) : (
              // while waiting on API response, display this
              // below code generated by https://loading.io/
              <div className="loadingio-spinner-bean-eater-zwyhx5ec3yq"><div className="ldio-wa7k0r94wz9">
                <div className=""><div></div><div></div><div></div></div><div><div></div><div></div><div></div></div>
              </div></div>
            )}
          </>
        }
        {submitError && (<div className="text-red-600 ms-2 poppins">
          {submitError}
        </div>)
        }
      </div>
    </div>
  )
}



